server:
  port: 8087

spring:
  application:
    name: "RabbitMqRead"
  main:
    web-application-type: "reactive"
  rabbitmq:
    host: "0.0.0.0"
    port: 5672
    username: "admin"
    password: "admin"
    virtual-host: "/"    
       