server:
  port: 8089
spring:
  application:
    name: "RpcClientRabbit2"
  main:
    web-application-type: "reactive"

  rabbitmq:
    host: "0.0.0.0"
    port: 5673
    username: "jaamurci"
    password: "JAmbg172"
    virtualhost: "/"
