server:
  port: 8088
spring:
  application:
    name: "RpcClientRabbit"
  main:
    web-application-type: "reactive"

  rabbitmq:
    host: "192.168.10.29"
    port: 5672
    username: "admin"
    password: "admin"
    virtualhost: "/"
